"""esquema completo tesisguard

Revision ID: 7f43134b7e86
Revises:
Create Date: 2026-06-14 15:20:45.576980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# Identificadores de revisión usados por Alembic.
revision: str = "7f43134b7e86"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_suscripcion",
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("precio", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("periodo_dias", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "rol", sa.Enum("ESTUDIANTE", "ADMINISTRADOR", name="rol_usuario"), nullable=False
        ),
        sa.Column("foto_perfil_url", sa.String(length=500), nullable=True),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuario_email"), "usuario", ["email"], unique=True)
    op.create_table(
        "avance_formal",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("etapa", sa.String(length=120), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "APROBADO", "RECHAZADO", name="estado_avance"),
            nullable=False,
        ),
        sa.Column("aprobado_por_id", sa.BigInteger(), nullable=True),
        sa.Column("fecha_aprobacion", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["aprobado_por_id"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_avance_formal_aprobado_por_id"), "avance_formal", ["aprobado_por_id"], unique=False
    )
    op.create_index(
        op.f("ix_avance_formal_usuario_id"), "avance_formal", ["usuario_id"], unique=False
    )
    op.create_table(
        "bitacora",
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("accion", sa.String(length=120), nullable=False),
        sa.Column("entidad", sa.String(length=120), nullable=False),
        sa.Column("entidad_id", sa.BigInteger(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bitacora_actor_id"), "bitacora", ["actor_id"], unique=False)
    op.create_table(
        "documento",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documento_usuario_id"), "documento", ["usuario_id"], unique=False)
    op.create_table(
        "suscripcion",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "ACTIVA", "EXPIRADA", "CANCELADA", name="estado_suscripcion"),
            nullable=False,
        ),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=True),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_suscripcion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suscripcion_plan_id"), "suscripcion", ["plan_id"], unique=False)
    op.create_index(op.f("ix_suscripcion_usuario_id"), "suscripcion", ["usuario_id"], unique=False)
    op.create_table(
        "token_reset_password",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_token_reset_password_usuario_id"),
        "token_reset_password",
        ["usuario_id"],
        unique=False,
    )
    op.create_table(
        "pago",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("suscripcion_id", sa.BigInteger(), nullable=True),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column(
            "estado",
            sa.Enum("PENDIENTE", "PAGADO", "FALLIDO", "REEMBOLSADO", name="estado_pago"),
            nullable=False,
        ),
        sa.Column("stripe_checkout_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan_suscripcion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suscripcion_id"],
            ["suscripcion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_checkout_session_id"),
    )
    op.create_index(op.f("ix_pago_plan_id"), "pago", ["plan_id"], unique=False)
    op.create_index(op.f("ix_pago_suscripcion_id"), "pago", ["suscripcion_id"], unique=False)
    op.create_index(op.f("ix_pago_usuario_id"), "pago", ["usuario_id"], unique=False)
    op.create_table(
        "version_documento",
        sa.Column("documento_id", sa.BigInteger(), nullable=False),
        sa.Column("numero_version", sa.Integer(), nullable=False),
        sa.Column("archivo_url", sa.String(length=500), nullable=False),
        sa.Column("formato", sa.Enum("DOCX", "PDF", name="formato_documento"), nullable=False),
        sa.Column(
            "estado_analisis",
            sa.Enum("PENDIENTE", "EN_PROCESO", "COMPLETADO", "ERROR", name="estado_analisis"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_version_documento_documento_id"),
        "version_documento",
        ["documento_id"],
        unique=False,
    )
    op.create_table(
        "alerta_etica",
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(length=120), nullable=False),
        sa.Column("fragmento", sa.Text(), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "PENDIENTE", "EN_REVISION", "CONFIRMADA", "DESESTIMADA", name="estado_alerta_etica"
            ),
            nullable=False,
        ),
        sa.Column("decision_admin_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_admin_id"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["version_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerta_etica_decision_admin_id"),
        "alerta_etica",
        ["decision_admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alerta_etica_version_id"), "alerta_etica", ["version_id"], unique=False
    )
    op.create_table(
        "evento_webhook",
        sa.Column("stripe_event_id", sa.String(length=255), nullable=False),
        sa.Column("pago_id", sa.BigInteger(), nullable=True),
        sa.Column("tipo", sa.String(length=120), nullable=False),
        sa.Column("processed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["pago_id"],
            ["pago.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_event_id"),
    )
    op.create_index(op.f("ix_evento_webhook_pago_id"), "evento_webhook", ["pago_id"], unique=False)
    op.create_table(
        "resultado_auditoria",
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "nivel_documento",
            sa.Enum("ALTO", "MEDIO", "BAJO", name="nivel_preparacion"),
            nullable=False,
        ),
        sa.Column("resumen", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["version_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_id"),
    )
    op.create_table(
        "sesion_simulacion",
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("version_documento_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "nivel_dificultad",
            sa.Enum("EXPLORACION", "ESTANDAR", "RIGUROSO", name="nivel_dificultad"),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum("EN_CURSO", "FINALIZADA", "CANCELADA", name="estado_sesion"),
            nullable=False,
        ),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_documento_id"],
            ["version_documento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sesion_simulacion_usuario_id"), "sesion_simulacion", ["usuario_id"], unique=False
    )
    op.create_index(
        op.f("ix_sesion_simulacion_version_documento_id"),
        "sesion_simulacion",
        ["version_documento_id"],
        unique=False,
    )
    op.create_table(
        "metrica_biometrica",
        sa.Column("sesion_id", sa.BigInteger(), nullable=False),
        sa.Column("postura_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("muletillas_conteo", sa.Integer(), nullable=False),
        sa.Column("ritmo_wpm", sa.Integer(), nullable=True),
        sa.Column("contacto_visual_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("momento", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesion_simulacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metrica_biometrica_sesion_id"), "metrica_biometrica", ["sesion_id"], unique=False
    )
    op.create_table(
        "observacion",
        sa.Column("resultado_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "categoria",
            sa.Enum("COHERENCIA", "NORMAS", "SUGERENCIA", name="categoria_observacion"),
            nullable=False,
        ),
        sa.Column("severidad", sa.String(length=20), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=False),
        sa.Column("ubicacion", sa.String(length=255), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["resultado_id"],
            ["resultado_auditoria.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observacion_resultado_id"), "observacion", ["resultado_id"], unique=False
    )
    op.create_table(
        "pregunta_tribunal",
        sa.Column("sesion_id", sa.BigInteger(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesion_simulacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pregunta_tribunal_sesion_id"), "pregunta_tribunal", ["sesion_id"], unique=False
    )
    op.create_table(
        "resultado_simulacion",
        sa.Column("sesion_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "nivel_defensa", sa.Enum("ALTO", "MEDIO", "BAJO", name="nivel_defensa"), nullable=False
        ),
        sa.Column("oratoria_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("comunicacion_no_verbal_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("dominio_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("resumen", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesion_simulacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sesion_id"),
    )
    op.create_table(
        "respuesta_estudiante",
        sa.Column("pregunta_id", sa.BigInteger(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=True),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["pregunta_id"],
            ["pregunta_tribunal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pregunta_id"),
    )
    op.create_table(
        "evaluacion_respuesta",
        sa.Column("respuesta_id", sa.BigInteger(), nullable=False),
        sa.Column("puntuacion", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("profundidad", sa.String(length=20), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["respuesta_id"],
            ["respuesta_estudiante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("respuesta_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluacion_respuesta")
    op.drop_table("respuesta_estudiante")
    op.drop_table("resultado_simulacion")
    op.drop_index(op.f("ix_pregunta_tribunal_sesion_id"), table_name="pregunta_tribunal")
    op.drop_table("pregunta_tribunal")
    op.drop_index(op.f("ix_observacion_resultado_id"), table_name="observacion")
    op.drop_table("observacion")
    op.drop_index(op.f("ix_metrica_biometrica_sesion_id"), table_name="metrica_biometrica")
    op.drop_table("metrica_biometrica")
    op.drop_index(op.f("ix_sesion_simulacion_version_documento_id"), table_name="sesion_simulacion")
    op.drop_index(op.f("ix_sesion_simulacion_usuario_id"), table_name="sesion_simulacion")
    op.drop_table("sesion_simulacion")
    op.drop_table("resultado_auditoria")
    op.drop_index(op.f("ix_evento_webhook_pago_id"), table_name="evento_webhook")
    op.drop_table("evento_webhook")
    op.drop_index(op.f("ix_alerta_etica_version_id"), table_name="alerta_etica")
    op.drop_index(op.f("ix_alerta_etica_decision_admin_id"), table_name="alerta_etica")
    op.drop_table("alerta_etica")
    op.drop_index(op.f("ix_version_documento_documento_id"), table_name="version_documento")
    op.drop_table("version_documento")
    op.drop_index(op.f("ix_pago_usuario_id"), table_name="pago")
    op.drop_index(op.f("ix_pago_suscripcion_id"), table_name="pago")
    op.drop_index(op.f("ix_pago_plan_id"), table_name="pago")
    op.drop_table("pago")
    op.drop_index(op.f("ix_token_reset_password_usuario_id"), table_name="token_reset_password")
    op.drop_table("token_reset_password")
    op.drop_index(op.f("ix_suscripcion_usuario_id"), table_name="suscripcion")
    op.drop_index(op.f("ix_suscripcion_plan_id"), table_name="suscripcion")
    op.drop_table("suscripcion")
    op.drop_index(op.f("ix_documento_usuario_id"), table_name="documento")
    op.drop_table("documento")
    op.drop_index(op.f("ix_bitacora_actor_id"), table_name="bitacora")
    op.drop_table("bitacora")
    op.drop_index(op.f("ix_avance_formal_usuario_id"), table_name="avance_formal")
    op.drop_index(op.f("ix_avance_formal_aprobado_por_id"), table_name="avance_formal")
    op.drop_table("avance_formal")
    op.drop_index(op.f("ix_usuario_email"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_table("plan_suscripcion")
    # ### end Alembic commands ###
